### PR TITLE
Fixed set environment path

### PR DESCRIPTION
**Pull request by ja7ad**
- Fixed Program path for none administrator
- changed `setx `, `set` environment path

### CODE REVIEW

**Comment by parsampsh** [comment]
Thank you so much! i think this will work. but the shell is bash and i think %varname%s should be changed to $varname. am i right?

**Comment by ja7ad** [comment]
> Thank you so much! i think this will work. but the shell is bash and i think %varname%s should be changed to $varname. am i right?

Sure , Windows having some global variable ex `%UserProfile% %appdata% ...`

user profile is : `C:\Users\user\`
appdata is :` C:\Users\user\Appdata\roaming\`
local appdata is : ` C:\Users\user\Appdata\local\`

**Comment by parsampsh** [comment]
well. wait a minute to i test it.

**Comment by parsampsh** [comment]
i tested both (`$` and `%`).  none of them didn't worked.

**Comment by parsampsh** [comment]
anyway, i'll merge it. maybe i fix it later :)
Thank you so much again.

**Comment by ja7ad** [comment]
> i tested both (`$` and `%`). none of them didn't worked.

Windows Doesn't support `$` for var just `%`

https://gist.github.com/pkfrom/f6eb82316b725a51f357

**Comment by parsampsh** [comment]
no problem. i changed the plan. see https://github.com/pashmaklang/setup-pashmak/commit/c46c85c7c4adcc714adcfe717a4e1a9e84d75488

**Pull request merged**
